version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db

  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
#    volumes:
#      - database:/var/lib/rabbitmq
    ports:
      - "5672:5672"



  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=sklep_internetowy
      - POSTGRES_USER=sklep
      - POSTGRES_PASSWORD=sklep123
    ports:
      - "5432:5432"





