version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=sklep_internetowy
      - POSTGRES_USER=sklep
      - POSTGRES_PASSWORD=sklep123
    ports:
      - "127.0.0.1:5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db




