# Generated by Django 3.2.8 on 2022-01-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienia',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
