# Generated by Django 3.2.9 on 2022-01-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamowienia',
            options={'ordering': ('-id',)},
        ),
    ]
